---

foo: bar

postgresql_users:
  - name: postgres
    password: r3dh4t1!

postgresql_version: 13

postgresql_global_config_options:

  - option: listen_addresses
    value: '*'

  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
 
  - option: log_directory
    value: 'log'

postgresql_hba_entries:
  
  - type: local
    database: all
    user: postgres
    auth_method: peer

  - type: local
    database: all
    user: all
    auth_method: peer

  - type: host
    database: all
    user: all
    address: '127.0.0.1/32'
    auth_method: md5

  - type: host
    database: all
    user: all
    address: '::1/128'
    auth_method: md5
  
  - type: host
    database: all
    user: all
    address: '0.0.0.0/0'
    auth_method: md5


# postgresql_conf:
#   - listen_addresses: "'*'"
#
# postgresql_pg_hba_conf:
#   - "local all all md5"
#   - "host all all 192.168.0.0/24 md5"
